version: 2

jobs:
  build:
    working_directory: ~/circleci-parrot-standup
    docker:
      - image: circleci/python

    steps:
      - checkout
      - run:
          name: "Install and execute pipenv"
          command: |
            sudo pip install pipenv
            pipenv install --dev
